# Generated by Django 3.2.12 on 2022-03-11 14:52

import django.core.serializers.json
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0067_customfield_min_max_values'),
        ('netbox_example_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
