# Generated by Django 3.2.12 on 2022-03-12 11:39

from django.db import migrations, models
import netbox_example_plugin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_example_plugin', '0002_auto_20220311_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=64, validators=[netbox_example_plugin.validators.name_validator]),
        ),
    ]
